-- 코드를 작성해주세요
SELECT ii2.ITEM_ID, ii2.ITEM_NAME, ii2.RARITY
FROM ITEM_INFO ii
    JOIN ITEM_TREE it ON ii.ITEM_ID = it.PARENT_ITEM_ID
    JOIN ITEM_INFO ii2 ON it.ITEM_ID = ii2.ITEM_ID
WHERE ii.RARITY = "RARE"
ORDER BY ii2.ITEM_ID DESC
